version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy_network

  app1:
    image: nik786/go_app_v1
    container_name: app_v1
    networks:
      - proxy_network

  app2:
    image: nik786/go_app_v2
    container_name: app_v2
    networks:
      - proxy_network

networks:
  proxy_network:

