version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    
    networks:
      - proxy_network


  app1:
    image: nik786/go_app_v1:v1
    container_name: app_v1
    ports:
      - "8080:8080"      
    networks:
      - proxy_network

  


networks:
  proxy_network:       


